apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/build-id: '3'
    fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
    fabric8.io/git-branch: release-v2.2.265
    fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/git-url: >-
      http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/iconUrl: >-
      https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus/src/main/fabric8/icon.png
    fabric8.io/metrics-path: >-
      dashboard/file/kubernetes-pods.json/?var-project=prometheus&var-version=2.2.265
  labels:
    group: io.fabric8.devops.apps
    project: prometheus
    provider: fabric8
    version: 2.2.265
  name: prometheus
spec:
  replicas: 1
  selector:
    group: io.fabric8.devops.apps
    project: prometheus
    provider: fabric8
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/build-id: '3'
        fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
        fabric8.io/git-branch: release-v2.2.265
        fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/git-url: >-
          http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/iconUrl: >-
          https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus/src/main/fabric8/icon.png
        fabric8.io/metrics-path: >-
          dashboard/file/kubernetes-pods.json/?var-project=prometheus&var-version=2.2.265
      labels:
        group: io.fabric8.devops.apps
        project: prometheus
        provider: fabric8
        version: 2.2.265
    spec:
      containers:
        - args:
            - '-config.file=/etc/prometheus/config/prometheus.yml'
            - '-storage.local.path=/prometheus'
            - '-web.console.libraries=/etc/prometheus/console_libraries'
            - '-web.console.templates=/etc/prometheus/consoles'
            - '-log.level=debug'
            - '-query.timeout=5m0s'
            - '-storage.local.retention=168h0m0s'
          image: 'prom/prometheus:v1.2.1'
          livenessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 1
          name: prometheus
          ports:
            - containerPort: 9090
              name: http
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 1
          volumeMounts:
            - mountPath: /etc/prometheus/config
              name: config-volume
            - mountPath: /prometheus
              name: data-volume
              subPath: prometheus-db
        - args:
            - '-volume-dir'
            - /etc/prometheus/config
            - '-webhook-url'
            - 'http://localhost:9090/-/reload'
          image: 'jimmidyson/configmap-reload:v0.1'
          name: configmap-reload
          volumeMounts:
            - mountPath: /etc/prometheus/config
              name: config-volume
      serviceAccountName: metrics
      volumes:
        - configMap:
            name: prometheus
          name: config-volume
        - name: data-volume
          persistentVolumeClaim:
            claimName: prometheus-claim
  triggers:
    - type: ConfigChange
endGroup: false
newGroup: false
